services:
  backend:
    build:
      context: ./backend
    container_name: planner-backend
    ports:
      - "8001:8000"
    volumes:
      - ./backend/data:/app/data

  frontend:
    build:
      context: ./frontend
    container_name: planner-frontend
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:8001
    ports:
      - "2005:5173"
